In [5]:
from sklearn.datasets import load_boston
boston = load_boston()

In [6]:
type(boston)

sklearn.utils.Bunch

In [9]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [10]:
type(boston['data'])

numpy.ndarray

In [11]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'],
      dtype='<U7')

In [12]:
print(boston['DESCR'])

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [13]:
from sklearn.ensemble import RandomForestRegressor

In [14]:
clf = RandomForestRegressor()

In [15]:
clf.fit(boston['data'],boston['target'])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [17]:
clf.score(boston['data'],boston['target'])

0.97466447664795708

In [18]:
clf.score?

In [19]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_estimator_type',
 '_get_param_names',
 '_make_estimator',
 '_set_oob_score',
 '_validate_X_predict',
 '_validate_estimator',
 '_validate_y_class_weight',
 'apply',
 'base_estimator',
 'base_estimator_',
 'bootstrap',
 'class_weight',
 'criterion',
 'decision_path',
 'estimator_params',
 'estimators_',
 'feature_importances_',
 'fit',
 'get_params',
 'max_depth',
 'max_features',
 'max_leaf_nodes',
 'min_impurity_decrease',
 'min_impuri

In [20]:
clf.n_features_

13

In [23]:
boston['data'].shape

(506, 13)

In [21]:
clf.n_outputs_

1

In [22]:
clf.feature_importances_

array([ 0.03528527,  0.00071966,  0.0080088 ,  0.00059235,  0.01899136,
        0.41053776,  0.0110226 ,  0.0741264 ,  0.00251677,  0.01865729,
        0.01664662,  0.00783621,  0.39505893])

In [26]:
row = boston['data'][17]
row.shape

(13,)

In [27]:
row.reshape(-1,13)

array([[   0.7842,    0.    ,    8.14  ,    0.    ,    0.538 ,    5.99  ,
          81.7   ,    4.2579,    4.    ,  307.    ,   21.    ,  386.75  ,
          14.67  ]])

In [28]:
clf.predict(row.reshape(-1,13))

array([ 17.44])

In [29]:
boston['target'][17]

17.5

# train/test split


In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test = train_test_split(boston['data'],boston['target'],test_size=0.3)

In [32]:
clf = RandomForestRegressor()
clf.fit(x_train, y_train)
clf.score(x_test,y_test)

0.83365613309304287

# Preprocessing

In [33]:
import pandas as pd


In [35]:
df = pd.DataFrame(boston['data'], columns = boston['feature_names'])
df.max(axis =0)

CRIM        88.9762
ZN         100.0000
INDUS       27.7400
CHAS         1.0000
NOX          0.8710
RM           8.7800
AGE        100.0000
DIS         12.1265
RAD         24.0000
TAX        711.0000
PTRATIO     22.0000
B          396.9000
LSTAT       37.9700
dtype: float64

In [36]:
from sklearn.svm import SVR

In [37]:
clf=SVR()
clf.fit(x_train, y_train)
clf.score(x_test,y_test)

0.012993598228493775

In [38]:
from sklearn import preprocessing
Xs = preprocessing.scale(boston['data'])

In [39]:
df = pd.DataFrame(Xs, columns = boston['feature_names'])
df.max(axis =0)

CRIM       9.941735
ZN         3.804234
INDUS      2.422565
CHAS       3.668398
NOX        2.732346
RM         3.555044
AGE        1.117494
DIS        3.960518
RAD        1.661245
TAX        1.798194
PTRATIO    1.638828
B          0.441052
LSTAT      3.548771
dtype: float64

In [42]:
Xs_train,Xs_test,ys_train,ys_test = train_test_split(Xs,boston['target'],test_size=0.3)

In [43]:
clf=SVR()
clf.fit(Xs_train, ys_train)
clf.score(Xs_test,ys_test)

0.62875968563771423

In [44]:
from sklearn.decomposition import PCA


In [45]:
pca = PCA(n_components =5)
pca.fit(boston['data'])

PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [47]:
Xp = pca.transform(boston['data'])
Xp.shape

(506, 5)

In [48]:
Xp_train,Xp_test,yp_train,yp_test = train_test_split(Xp,boston['target'],test_size=0.3)

In [49]:
clf = RandomForestRegressor()
clf.fit(Xp_train, yp_train)
clf.score(Xp_test,yp_test)

0.45171582580975922

In [51]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


In [52]:
pipe = Pipeline([
    ('scale',StandardScaler()),
    ('pca',PCA(n_components=5)),
    ('svr', SVR()),
])


In [56]:
x_train,x_test,y_train,y_test = train_test_split(boston['data'],boston['target'],test_size=0.3)

In [58]:
#sklearn only accepts data with rows and columns so the y_test and train are throwing an error
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(354, 13) (152, 13) (354,) (152,)


In [68]:

print(type(x_train))
print(type(x_test))
print(type(y_train))
print(type(y_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [69]:
pipe.fit(x_train,y_train)
pipe.score(x_test,y_test)

0.47014023063165977

In [70]:
pipe.steps

[('scale', StandardScaler(copy=True, with_mean=True, with_std=True)),
 ('pca',
  PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)),
 ('svr',
  SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False))]

In [71]:
pipe.get_params()

{'memory': None,
 'pca': PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
   svd_solver='auto', tol=0.0, whiten=False),
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': 5,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'scale': StandardScaler(copy=True, with_mean=True, with_std=True),
 'scale__copy': True,
 'scale__with_mean': True,
 'scale__with_std': True,
 'steps': [('scale', StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('pca',
   PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
     svd_solver='auto', tol=0.0, whiten=False)),
  ('svr',
   SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
     kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False))],
 'svr': SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
   kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False),
 's

In [72]:
dir(pipe)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_estimator_type',
 '_final_estimator',
 '_fit',
 '_get_param_names',
 '_get_params',
 '_inverse_transform',
 '_pairwise',
 '_replace_estimator',
 '_set_params',
 '_transform',
 '_validate_names',
 '_validate_steps',
 'classes_',
 'decision_function',
 'fit',
 'fit_predict',
 'fit_transform',
 'get_params',
 'inverse_transform',
 'memory',
 'named_steps',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'score',
 'set_params',
 'steps',
 'transform']

In [73]:
pipe.set_params(svr__C =0.9)

Pipeline(memory=None,
     steps=[('scale', StandardScaler(copy=True, with_mean=True, with_std=True)), ('pca', PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)), ('svr', SVR(C=0.9, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False))])

# Pickle Save and Load models

In [74]:
import pickle

In [75]:
# write binary.
with open('model.pickle', 'wb') as out:
    pickle.dump(pipe,out)

In [76]:
#read binary.
with open('model.pickle', 'rb') as fp:
    pipe1 = pickle.load(fp)

In [77]:
pipe1.steps

[('scale', StandardScaler(copy=True, with_mean=True, with_std=True)),
 ('pca',
  PCA(copy=True, iterated_power='auto', n_components=5, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)),
 ('svr',
  SVR(C=0.9, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False))]

In [78]:
pipe1.score(x_test,y_test)

0.47014023063165977